baseURL = 'https://tyxkk2.github.io/'
languageCode = 'zh-cn'
title = 'Yuxuan Tang'
theme = 'PaperMod'

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

[params.profileMode]
  enabled = true
  title = "Yuxuan Tang"
  subtitle = "Tsinghua CS undergraduate · CS · AI"
  imageUrl = "images/avatar.jpg"
  imageTitle = "avatar"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/tyxkk2"

[[params.socialIcons]]
  name = "email"
  url = "mailto:tyxkk2@gmail.com"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/tyxkk2"

[[params.socialIcons]]
  name = "bilibili"
  url = "https://space.bilibili.com/163827523"

[[params.profileMode.buttons]]
  name = "Blog"
  url = "/posts"

[[params.profileMode.buttons]]
  name = "About"
  url = "/about"

[[menus.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menus.main]]
  name = "Blog"
  url = "/posts/"
  weight = 20

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 30
